-- 为所有用户填充出行、食物、水电种子数据（随机条数、随机数值）
-- 直接在云库执行此脚本即可，无需改代码。

SET NOCOUNT ON;

-- ========== 1. 出行 TravelLogs ==========
;WITH Addr(i, addr, lat, lng) AS (
    SELECT 0, N'Orchard Rd, Singapore', 1.3042, 103.8318 UNION ALL
    SELECT 1, N'Marina Bay, Singapore', 1.2834, 103.8607 UNION ALL
    SELECT 2, N'Chinatown, Singapore', 1.2838, 103.8443 UNION ALL
    SELECT 3, N'Sentosa, Singapore', 1.2494, 103.8123 UNION ALL
    SELECT 4, N'Jurong East, Singapore', 1.3332, 103.7423 UNION ALL
    SELECT 5, N'Woodlands, Singapore', 1.4382, 103.7891 UNION ALL
    SELECT 6, N'Tampines, Singapore', 1.3526, 103.9385 UNION ALL
    SELECT 7, N'Bishan, Singapore', 1.3506, 103.8484 UNION ALL
    SELECT 8, N'Ang Mo Kio, Singapore', 1.3698, 103.8496 UNION ALL
    SELECT 9, N'Clementi, Singapore', 1.3342, 103.7745
),
Nums(n) AS (
    SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
    UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
    UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55
),
PerUser AS (
    SELECT u.Id AS UserId, n.n,
           ABS(CHECKSUM(NEWID())) % 10 AS Mode,
           (0.5 + (ABS(CHECKSUM(NEWID())) % 8000) / 100.0) AS DistKm,
           ABS(CHECKSUM(NEWID())) % 10 AS OIdx,
           (ABS(CHECKSUM(NEWID())) % 9) + 1 AS DOff
    FROM ApplicationUsers u
    CROSS JOIN Nums n
    WHERE n.n <= 20 + (ABS(CHECKSUM(u.Id)) % 36)
),
RowsWithAddr AS (
    SELECT p.UserId, p.Mode, p.DistKm,
           o.addr AS OAddr, o.lat AS OLat, o.lng AS OLng,
           d.addr AS DAddr, d.lat AS DLat, d.lng AS DLng,
           DATEADD(DAY, -(ABS(CHECKSUM(NEWID())) % 700), GETUTCDATE()) AS CreatedAt
    FROM PerUser p
    INNER JOIN Addr o ON o.i = p.OIdx
    INNER JOIN Addr d ON d.i = (p.OIdx + p.DOff) % 10
),
CarbonFactor AS (
    SELECT Mode, CASE Mode
        WHEN 0 THEN 0.0 WHEN 1 THEN 0.0 WHEN 2 THEN 0.12 WHEN 3 THEN 0.03 WHEN 4 THEN 0.05
        WHEN 5 THEN 0.15 WHEN 6 THEN 0.20 WHEN 7 THEN 0.05 WHEN 8 THEN 0.15 WHEN 9 THEN 0.25
        ELSE 0.10 END AS F
    FROM (SELECT 0 Mode UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) m
)
INSERT INTO TravelLogs (UserId, TransportMode, OriginAddress, OriginLatitude, OriginLongitude, DestinationAddress, DestinationLatitude, DestinationLongitude, DistanceMeters, DistanceKilometers, DurationSeconds, CarbonEmission, CreatedAt, UpdatedAt)
SELECT r.UserId, r.Mode, r.OAddr, r.OLat, r.OLng, r.DAddr, r.DLat, r.DLng,
       CAST(r.DistKm * 1000 AS INT), ROUND(r.DistKm, 2),
       CAST(r.DistKm * 1000 / 20 AS INT) + ABS(CHECKSUM(NEWID())) % 600,
       ROUND(r.DistKm * c.F, 4), r.CreatedAt, r.CreatedAt
FROM RowsWithAddr r
INNER JOIN CarbonFactor c ON c.Mode = r.Mode;

PRINT 'TravelLogs inserted: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

-- ========== 2. 食物 FoodRecords（名称与因子简表）==========
;WITH FoodList(idx, Name, Factor) AS (
    SELECT 0, N'Fried Rice', 0.90 UNION ALL SELECT 1, N'Laksa', 1.30 UNION ALL SELECT 2, N'Chicken Rice', 1.10 UNION ALL
    SELECT 3, N'Ramen', 1.40 UNION ALL SELECT 4, N'Pho', 1.50 UNION ALL SELECT 5, N'Dim Sum', 1.00 UNION ALL
    SELECT 6, N'Pizza', 1.40 UNION ALL SELECT 7, N'Hamburger', 3.50 UNION ALL SELECT 8, N'Sushi', 0.80 UNION ALL
    SELECT 9, N'Bubble Tea', 0.40 UNION ALL SELECT 10, N'Mapo Tofu', 0.60 UNION ALL SELECT 11, N'Nasi Lemak', 1.30 UNION ALL
    SELECT 12, N'Pad Thai', 1.00 UNION ALL SELECT 13, N'Steak', 5.00 UNION ALL SELECT 14, N'Fish and Chips', 1.40 UNION ALL
    SELECT 15, N'Caesar Salad', 0.70 UNION ALL SELECT 16, N'Hot Pot', 2.50 UNION ALL SELECT 17, N'Dumplings', 0.80 UNION ALL
    SELECT 18, N'Ice Cream', 1.00 UNION ALL SELECT 19, N'Kimchi', 0.20 UNION ALL SELECT 20, N'Miso Soup', 0.20 UNION ALL
    SELECT 21, N'French Fries', 0.60 UNION ALL SELECT 22, N'Pancakes', 0.70 UNION ALL SELECT 23, N'Spaghetti', 2.00 UNION ALL
    SELECT 24, N'Grilled Salmon', 1.40 UNION ALL SELECT 25, N'Tom Yum Soup', 0.90 UNION ALL SELECT 26, N'Satay', 1.50 UNION ALL
    SELECT 27, N'Spring Rolls', 0.50 UNION ALL SELECT 28, N'Cheesecake', 1.50 UNION ALL SELECT 29, N'Greek Salad', 0.60
),
Nums(n) AS (
    SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
    UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL SELECT 50
    UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL SELECT 60
    UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL SELECT 70
    UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74 UNION ALL SELECT 75 UNION ALL SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL SELECT 79 UNION ALL SELECT 80
    UNION ALL SELECT 81 UNION ALL SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84 UNION ALL SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL SELECT 88 UNION ALL SELECT 89 UNION ALL SELECT 90
),
PerUserFood AS (
    SELECT u.Id AS UserId, n.n,
           ABS(CHECKSUM(NEWID())) % 30 AS FIdx,
           (0.05 + (ABS(CHECKSUM(NEWID())) % 56) / 100.0) AS AmountKg,
           DATEADD(DAY, -(ABS(CHECKSUM(NEWID())) % 400), GETUTCDATE()) AS CreatedAt
    FROM ApplicationUsers u
    CROSS JOIN Nums n
    WHERE n.n <= 35 + (ABS(CHECKSUM(u.Id * 3)) % 56)
)
INSERT INTO FoodRecords (UserId, Name, Amount, EmissionFactor, Emission, CreatedAt, UpdatedAt)
SELECT p.UserId, f.Name, ROUND(p.AmountKg, 3), f.Factor, ROUND(p.AmountKg * f.Factor, 4), p.CreatedAt, p.CreatedAt
FROM PerUserFood p
INNER JOIN FoodList f ON f.idx = p.FIdx;

PRINT 'FoodRecords inserted: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

-- ========== 3. 水电 UtilityBills ==========
;WITH Nums(n) AS (
    SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
),
PerUserUtil AS (
    SELECT u.Id AS UserId, n.n,
           ABS(CHECKSUM(NEWID())) % 4 AS BillType,
           ABS(CHECKSUM(NEWID())) % 28 AS MonthOffset,
           ABS(CHECKSUM(NEWID())) % 10 AS DayOffset
    FROM ApplicationUsers u
    CROSS JOIN Nums n
    WHERE n.n <= 12 + (ABS(CHECKSUM(u.Id * 7)) % 19)
),
Bills AS (
    SELECT UserId,
           BillType,
           EOMONTH(DATEADD(MONTH, -MonthOffset, GETUTCDATE())) AS PeriodEnd,
           DATEADD(DAY, DayOffset, EOMONTH(DATEADD(MONTH, -MonthOffset, GETUTCDATE()))) AS CreatedAt
    FROM PerUserUtil
),
BillsWithStart AS (
    SELECT UserId, BillType, PeriodEnd,
           DATEFROMPARTS(YEAR(PeriodEnd), MONTH(PeriodEnd), 1) AS PeriodStart,
           CreatedAt
    FROM Bills
),
WithUsage AS (
    SELECT b.*,
           CASE WHEN b.BillType IN (0, 3) THEN 80.0 + (ABS(CHECKSUM(NEWID())) % 320) / 1.0 ELSE 0 END AS ElecUsage,
           CASE WHEN b.BillType IN (1, 3) THEN 5.0 + (ABS(CHECKSUM(NEWID())) % 250) / 10.0 ELSE 0 END AS WaterUsage,
           CASE WHEN b.BillType IN (2, 3) THEN 10.0 + (ABS(CHECKSUM(NEWID())) % 400) / 10.0 ELSE 0 END AS GasUsage
    FROM BillsWithStart b
)
INSERT INTO UtilityBills (UserId, YearMonth, BillType, BillPeriodStart, BillPeriodEnd, ElectricityUsage, ElectricityCost, WaterUsage, WaterCost, GasUsage, GasCost, ElectricityCarbonEmission, WaterCarbonEmission, GasCarbonEmission, TotalCarbonEmission, InputMethod, CreatedAt, UpdatedAt)
SELECT w.UserId,
       FORMAT(w.PeriodEnd, 'yyyy-MM'),
       w.BillType,
       w.PeriodStart,
       w.PeriodEnd,
       NULLIF(ROUND(w.ElecUsage, 4), 0),
       ROUND(CASE WHEN w.ElecUsage > 0 THEN w.ElecUsage * (0.2 + (ABS(CHECKSUM(NEWID())) % 16) / 100.0) ELSE 0 END, 2),
       NULLIF(ROUND(w.WaterUsage, 4), 0),
       ROUND(CASE WHEN w.WaterUsage > 0 THEN w.WaterUsage * (1.2 + (ABS(CHECKSUM(NEWID())) % 50) / 100.0) ELSE 0 END, 2),
       NULLIF(ROUND(w.GasUsage, 4), 0),
       ROUND(CASE WHEN w.GasUsage > 0 THEN w.GasUsage * (0.3 + (ABS(CHECKSUM(NEWID())) % 20) / 100.0) ELSE 0 END, 2),
       ROUND(CASE WHEN w.ElecUsage > 0 THEN w.ElecUsage * 0.4 ELSE 0 END, 4),
       ROUND(CASE WHEN w.WaterUsage > 0 THEN w.WaterUsage * 0.2 ELSE 0 END, 4),
       ROUND(CASE WHEN w.GasUsage > 0 THEN w.GasUsage * 0.2 ELSE 0 END, 4),
       ROUND(CASE WHEN w.ElecUsage > 0 THEN w.ElecUsage * 0.4 ELSE 0 END, 4) + ROUND(CASE WHEN w.WaterUsage > 0 THEN w.WaterUsage * 0.2 ELSE 0 END, 4) + ROUND(CASE WHEN w.GasUsage > 0 THEN w.GasUsage * 0.2 ELSE 0 END, 4),
       1,
       w.CreatedAt,
       w.CreatedAt
FROM WithUsage w;

PRINT 'UtilityBills inserted: ' + CAST(@@ROWCOUNT AS NVARCHAR(20));

-- ========== 4. 更新所有用户总碳排放 ==========
UPDATE ApplicationUsers
SET TotalCarbonEmission = (
    ISNULL((SELECT SUM(TotalEmission) FROM ActivityLogs WHERE ActivityLogs.UserId = ApplicationUsers.Id), 0) +
    ISNULL((SELECT SUM(CarbonEmission) FROM TravelLogs WHERE TravelLogs.UserId = ApplicationUsers.Id), 0) +
    ISNULL((SELECT SUM(TotalCarbonEmission) FROM UtilityBills WHERE UtilityBills.UserId = ApplicationUsers.Id), 0)
);

PRINT 'ApplicationUsers.TotalCarbonEmission updated for all users.';
PRINT 'Done.';
